export const REQUEST_QUESTIONS = './REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS = './RECEIVE_QUESTIONS';
export const REQUEST_CHOICES = './REQUEST_CHOICES';
export const RECEIVE_CHOICES = './RECEIVE_CHOICES';
export const TOGGLE_CHOICE = './TOGGLE_CHOICE';
export const TOGGLE_USER_CHECKLIST = './TOGGLE_USER_CHECKLIST';
export const REQUEST_SESSION_LOGIN = './REQUEST_SESSION_LOGIN';
export const RECEIVE_SESSION_LOGIN = './RECEIVE_SESSION_LOGIN';
export const REQUEST_UPSERT_CHOICES = './REQUEST_UPSERT_CHOICES';
export const RECEIVE_UPSERT_CHOICES = './RECEIVE_UPSERT_CHOICES';
export const REQUEST_CHECKLIST = './REQUEST_CHECKLIST';
export const RECEIVE_CHECKLIST = './RECEIVE_CHECKLIST';
export const REQUEST_USER_CHECKLIST = './REQUEST_USER_CHECKLIST';
export const RECEIVE_USER_CHECKLIST = './RECEIVE_USER_CHECKLIST';
export const REQUEST_CHECKLIST_STEPS = './REQUEST_CHECKLIST_STEPS';
export const RECEIVE_CHECKLIST_STEPS = './RECEIVE_CHECKLIST_STEPS';
export const CURRENT_STEP = './CURRENT_STEP';

